version: "3" 
# Defines which compose version to use
services:
  # Services line define which Docker images to run. In this case, it will be MySQL server and WordPress image.
  db:
    image: mysql:5.7
    # image: mysql:5.7 indicates the MySQL database container image from Docker Hub used in this installation.
    container_name: database
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wp_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: 123
      # Previous four lines define the main variables needed for the MySQL container to work: database, database username, database user password, and the MySQL root password.
  wordpress:
    container_name: wordpress
    depends_on:
      - db
      # - certbot
    image: wordpress:latest
    restart: always
    # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    ports:
      - "80:80"
      - "443:443"
      # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mysqluser
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wp_db
      # WORDPRESS_HTTPS: "true"
# Similar to MySQL image variables, the last four lines define the main variables needed for the WordPress container to work properly with the MySQL container.
    volumes:
      - ./wp-data:/var/www/html
      - ./wp-logs:/var/log/apache2
      - ./certbot/conf:/etc/letsencrypt
      - ./wp-conf/apache2:/etc/apache2
      # - ./certbot/logs:/var/log/letsencrypt
      # - ./certbot/data:/var/www/certbot
  certbot:
    depends_on: 
      - wordpress
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html --email dusan.jovanovic@qcerris.com --agree-tos -d dusan.qcerris.cloud
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./wp-data:/var/www/html
  grafana:
    depends_on:
      - wordpress
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: always
    ports:
      - "3000:3000"
    # volumes:
      # - ./grafana/data:/var/lib/grafana
      # - ./grafana/logs:/var/log/grafana
      # - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 123
      GF_SERVER_ROOT_URL: https://dusan.qcerris.cloud
      # GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
# volumes:
#   db_data: